### ISSUE TITLE
Returning IsoCode639_1

### ISSUE THREAD

**Issue by joshdehlong** [pemistahl/lingua-py#129]
Hello, is there any option to make lingua return the language as its IsoCode639_1 instead of Language.ENGLISH? In the API documentation I have found a class for it but no further information/an example on how to use it.

Thank you

**Comment by pemistahl** [comment]
There is an attribute on each `Language` that gives you the ISO code. 

```python
>>> from lingua import Language
>>> Language.ENGLISH.iso_code_639_1
IsoCode639_1.EN
>>> Language.ENGLISH.iso_code_639_1.name
'EN'
```

I'm surprised that this attribute is not listed in the generated API docs. Probably, it's because this is not a real class member but an attribute of an enum entry. I will try to find a better API docs generator or simplify the API somehow. The least I can do is to provide an example in the README.

Thank you for making me aware of this. :)
