### ISSUE TITLE
Yanked versions

### ISSUE THREAD

**Issue by punsoong-canva** [pemistahl/lingua-py#207]
Hi,

I see that you have deleted/yanked previous releases due to PyPI's project size limits.
This causes issues when a version matching is used i.e. `lingua-language-detector==2.0.0` and [Hash-checking Mode](https://pip.pypa.io/en/stable/topics/secure-installs/#hash-checking-mode)

Have you tried requesting an increase in the project limit here? https://github.com/pypi/support/issues/new/choose - see Size Limit Request (project-wide)

Thanks!

**Comment by pemistahl** [comment]
I'm sorry, I'm not happy about this problem either. A single release consumes 3.7 GB currently. I know it's possible to request an increase of the project limit. I just thought that my project is not important enough to get an increase. But I will try. If my request is denied, I will drop support for Python 3.8 and PyPy 3.8. This would save 1 GB.

There is 5.5 GB on PyPI left. When releasing 2.1.0, I won't yank 2.0.2. At least not at once. For now, you should not use 2.0.0 or 2.0.1 anymore anyway because they lack the type stubs and contain annoying bugs.

I will try to get an increase for the file-size limit as well. I'm planning to add more languages to the library but this will increase the wheel size significantly. The language models are currently stored as Brotli-compressed json files. This is the best compression method I could find. Every other combination of data format and compression method leads to even bigger files.

**Comment by pemistahl** [comment]
Alright, I have sent requests to increase the file size and project size limits. Keep your fingers crossed for me.

https://github.com/pypi/support/issues/3442

https://github.com/pypi/support/issues/3444

**Comment by pemistahl** [comment]
Good news: My requests have just been approved. That means, I won't have to yank releases anymore, at least not in the near future. :)

**Comment by punsoong-canva** [comment]
Fantastic! Thanks for following up on this!
